### ISSUE TITLE
How do I run the project?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [ngscheurich/udemy-love#1]
I like Moon, and I wanted to see this game in action! tanks

**Comment by ngscheurich** [comment]
These were made for a course using the LÖVE game engine, so you'll need to [download LÖVE](https://love2d.org/) to run them. After you've downloaded it, drag one of the three subdirectories onto the LÖVE executable to run it; alternatively, from a CLI, you can:

```
$ your/path/to/love directory
```

**Comment by JoseRFJuniorLLMs** [comment]
I already did and I've studied the whole game, do you have another project? I found the language very cool, I have always used JS for games, Lua is much simpler! Do you work with games? of the for the Firebase in the Game and by Machine Learning along with the Physics of the game?
